### ISSUE TITLE
Invalid request method, from Dart client

### ISSUE THREAD

**Issue by jkleiser** [oraoto/pony-websocket#1]
I have successfully used your pony-websocket in combination with web browser clients and a tiny Python client. However, when I try a simple stand-alone client (no browser) written in Dart, then Dart gives me this:
```
Unhandled exception:
HttpException: Invalid request method, uri = http://127.0.0.1:8989/
#0      _HttpParser._doParse (dart:io/http_parser.dart:428)
#1      _HttpParser._parse (dart:io/http_parser.dart:318)
#2      _HttpParser._onData (dart:io/http_parser.dart:804)
```
I notice two things, but they may not be significant:
1) The exception mentions "http:", not "ws:".
2) In the (pony) server log there's no "New client connected", just a "Connection closed".

My Dart client has no problem connecting to e.g. `ws://demos.kaazing.com/echo`. This far I have only tried this on macOS, but Dart should work equally well on Linux and Windows. (I may try it on Linux by using Docker.) Here's my Dart program:
```dart
import "dart:io";

// https://www.dartlang.org/dart-vm/dart-by-example#websockets
// https://api.dartlang.org/stable/1.24.2/dart-io/WebSocket-class.html

void receivedData(data) {
  print("Received: $data");
}

main() async {
  // https://api.dartlang.org/stable/1.24.2/dart-io/WebSocket/connect.html
  var socket = await WebSocket.connect("ws://127.0.0.1:8989/");
  
  // https://api.dartlang.org/stable/1.24.2/dart-async/Stream/listen.html
  socket.listen((data) {
    receivedData(data);
  });
  
  for (int i=1; i<4; i++) {
    socket.add("dart-$i"); // a String, or a List<int> holding bytes
  }
}
```
I cannot say for sure, of course, if the problem is in your pony-websocket or in Dart, but I would very much like to use those two together.

**Comment by oraoto** [comment]
I spend sometime installing dart in windows, and the problem reproduced.

The Dart client send http headers in lower case:

```
GET /ws HTTP/1.1
user-agent: Dart/1.24 (dart:io)
connection: Upgrade
cache-control: no-cache
accept-encoding: gzip
content-length: 0
sec-websocket-version: 13
host: 127.0.0.1:8989
sec-websocket-extensions: permessage-deflate; client_max_window_bits
sec-websocket-key: Zc0uS/ZIkuvhXgG+nhYzLA==
upgrade: websocket
```

But this library did not handle it correctly, so the handshake fails.

**Comment by oraoto** [comment]
I have make an quick fix(https://github.com/oraoto/pony-websocket/commit/f1a4f6fed764ddd538f3def9062f0a3d4b756333) to convert all headers to lower case.

**Comment by jkleiser** [comment]
Great! Now it works with my Dart client too. Thanks!

**Comment by jkleiser** [comment]
One question:
My current Dart client keeps listening till I do Ctrl-C. The Pony echo server, however, doesn't seem to discover that my client has quit, at least no "Connection closed" is printed. Is that just the way WebSockets work?

**Comment by oraoto** [comment]
When you Ctrl-C,  the TCP connection was closed directly without sending a close frame. The `TCPConnection` actually discover this case, but I did't pass the notification to the `WebSocketListenNotify`.

Another fix https://github.com/oraoto/pony-websocket/commit/f4421ae0ccccfa02cc398559437ccecb2137f7ea added.

**Comment by jkleiser** [comment]
Great! Now I get "Connection closed". Thanks!

**Comment by oraoto** [comment]
@jkleiser Thanks for your feedback to make pony-websocket better for real-world usage.
