### ISSUE TITLE
wsta - A CLI development tool for WebSocket APIs

### ISSUE THREAD

**Issue by jkleiser** [oraoto/pony-websocket#2]
I just discovered this CLI tool: https://github.com/esphen/wsta
It was mentioned in this blog post: https://zorbash.com/post/phoenix-websockets-under-a-microscope/
Just in case you don't already know wsta.

**Comment by oraoto** [comment]
Thanks for sharing wsta, it's a great tool to do simple websocket test. It will be great if wsta outputs frame details.
