### ISSUE TITLE
Alternative (simpler?) installation

### ISSUE THREAD

**Issue by montsamu** [oraoto/pony-websocket#3]
Instead of:

Installation
Install pony-stable
Update your bundle.json
{
  "type": "github",
  "repo": "oraoto/pony-websocket"
}
stable fetch

After installing pony-stable, the command "stable add github oraoto/pony-websocket" will do both the bundle.json update and the fetch.

**Comment by oraoto** [comment]
Thanks for this advice, I have updated the docs.
